name: Build and deploy Docker app to Azure

on: push

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# Set up the following secrets in your repository:
#   AZURE_CREDENTIALS, REGISTRY_USERNAME, REGISTRY_PASSWORD, REGISTRY_URL
# 2. Change these variables for your configuration:
env:
  AZURE_WEBAPP_NAME: PliyoWeb # set this to your application's name
# AZURE_RESOURCE_GROUP: ActionsDemo   # set this to your Azure Resource group's name - Needed only if you are provisioning the app in the workflow
# AZURE_APP_PLAN: ActionPlan  # set this to your App service plan's name - Needed only if you are provisioning the app in the workflow

jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS  }}
      #     - name: Azure CLI script to provision a new Web App for Container
      #       uses: azure/CLI@v0-beta
      #       with:
      #         azcliversion: latest
      #         inlineScript: |
      #           az webapp create --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --plan ${{ env.AZURE_APP_PLAN }} --name ${{ env.AZURE_WEBAPP_NAME }}  -i nginx
      - name: Publish to Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          repository: ${{ secrets.REGISTRY_URL }}/pliyoweb
          tags: latest
      - name: ACR authentication
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_URL }} # set secret with Container Registry URL, example : xyz.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        # - name: "Deploy to Azure Web App for Container"
        #   uses: azure/webapps-deploy@v2
        #   with:
        #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
        #     images: ${{ env.CONTAINER_REGISTRY }}/pliyoweb:${{ github.sha }}
