name: Build and deploy Docker app to Azure

on: push

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# Set up the following secrets in your repository:
#   AZURE_CREDENTIALS, REGISTRY_USERNAME, REGISTRY_PASSWORD, REGISTRY_URL
# 2. Change these variables for your configuration:
env:
  AZURE_WEBAPP_NAME: AppWithContainer # set this to your application's name
  CONTAINER_REGISTRY: ${{ secrets.REGISTRY_URL }} # set secret with Container Registry URL, example : xyz.azurecr.io

jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: ACR authentication
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Docker Build & Push to ACR
        run: |
          docker build . -t ${{ env.CONTAINER_REGISTRY }}/pliyoweb:${{ github.sha }}
          docker push ${{ env.CONTAINER_REGISTRY }}/pliyoweb:${{ github.sha }}
      # Uncomment the below action snippet if the Web app credentials are not updated as web app settings
      #     - name: Set Web App ACR authentication
      #       uses: Azure/appservice-settings@v1
      #       with:
      #         app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #         app-settings-json: |
      #           [
      #               {
      #                   "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
      #                   "value": "${{ secrets.REGISTRY_PASSWORD }}",
      #                   "slotSetting": false
      #               },
      #               {
      #                   "name": "DOCKER_REGISTRY_SERVER_URL",
      #                   "value": "https://${{ env.CONTAINER_REGISTRY }}",
      #                   "slotSetting": false
      #               },
      #               {
      #                   "name": "DOCKER_REGISTRY_SERVER_USERNAME",
      #                   "value": "${{ secrets.REGISTRY_USERNAME  }}",
      #                   "slotSetting": false
      #               }
      #           ]
      # - name: "Deploy to Azure Web App for Container"
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #     images: ${{ env.CONTAINER_REGISTRY }}/pliyoweb:${{ github.sha }}
